# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scifiui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1127, 865)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -70, 1111, 921))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("stars.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(350, 190, 411, 661))
        self.label_2.setStyleSheet("background:transperent;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("background.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 281, 61))
        self.textBrowser.setStyleSheet("background:transperent;color:rgb(222, 222, 222);\n"
"border-color: rgb(234, 234, 234);\n"
"font: 18pt \"8514oem\";")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(310, 0, 281, 61))
        self.textBrowser_2.setStyleSheet("font: 18pt \"8514oem\";\n"
"border-color: rgb(221, 221, 221);\n"
"background:transperent;\n"
"\n"
"color: rgb(212, 212, 212);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.start = QtWidgets.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(940, 30, 93, 28))
        self.start.setStyleSheet("font: 12pt \"Algerian\";color:rgb(255, 255, 255);\n"
"background:transperent;")
        self.start.setObjectName("start")
        self.start_2 = QtWidgets.QPushButton(Form)
        self.start_2.setGeometry(QtCore.QRect(940, 80, 93, 28))
        self.start_2.setStyleSheet("font: 12pt \"Algerian\";color:rgb(255, 255, 255);\n"
"background:transperent;")
        self.start_2.setObjectName("start_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start.setText(_translate("Form", "start"))
        self.start_2.setText(_translate("Form", "stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
